function e(d){console.log(d)}function _(d){return document.getElementById(d)}
function $(d){"string"==typeof d?this.element=document.querySelectorAll(d):"object"==typeof d&&(d.hasOwnProperty("hide")?this.element=d.element.slice():this.element[0]=d);this.CUSTOME=function(){};this._getStyle=function(a,b){var c;if((c=(a.ownerDocument||document).defaultView)&&c.getComputedStyle)return b=b.replace(/([A-Z])/g,"-$1").toLowerCase(),c.getComputedStyle(a,null).getPropertyValue(b);if(a.currentStyle)return b=b.replace(/\-(\w)/g,function(a,b){return b.toUpperCase()}),c=a.currentStyle[b],
/^\d+(em|pt|%|ex)?$/i.test(c)?function(b){var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b||0;b=a.style.pixelLeft+"px";a.style.left=c;a.runtimeStyle.left=d;return b}(c):c};this.elements=function(){return this.element};this.dump=function(){console.log(this.element)};this.hide=function(){for(var a=0;a<this.element.length;a++)this.element[a].style.display="none";return this};this.show=function(){for(var a=0;a<this.element.length;a++)this.element[a].style.display=
"block";return this};this.toggle=function(){for(var a=0;a<this.element.length;a++){var b=this.element[a];"none"==this._getStyle(b,"display")?b.style.display="block":b.style.display="none"}return this};this.text=function(){if(0==arguments.length)return this.element[0].innerHTML;for(var a=0;a<this.element.length;a++)this.element[a].innerHTML=arguments[0];return this};this.replace=function(a){for(var b=0;b<this.element.length;b++)this.element[b].outerHTML=a;return this};this.remove=function(){for(var a=
0;a<this.element.length;a++)this.element[a].outerHTML="";return this};this.append=function(a){for(var b=0;b<this.element.length;b++){var c=this.element[b];c.innerHTML+=a}return this};this.appendStart=function(a){for(var b=0;b<this.element.length;b++){var c=this.element[b];c.innerHTML=a+c.innerHTML}return this};this.css=function(){if(2===arguments.length)for(var a=0;a<this.element.length;a++){var b=this.element[a];b.style.cssText+=";"+arguments[0]+":"+arguments[1]+";"}else if(1===arguments.length)if(0<=
arguments[0].search(":")||0<=arguments[0].search(";"))for(a=0;a<this.element.length;a++)b=this.element[a],b.style.cssText+=";"+arguments[0]+";";else return this._getStyle(this.element[0],arguments[0]);return this};this.attr=function(){if(2===arguments.length)for(var a=0;a<this.element.length;a++){var b=this.element[a];b.setAttribute(arguments[0],arguments[1])}else if(1===arguments.length){e("ATTR "+this.element.length);if(0<this.element.length)return b=this.element[this.element.length-1],b.getAttribute(arguments[0]);
return}return this};this.val=function(){if(1===arguments.length)for(var a=0;a<this.element.length;a++)this.element[a].value=arguments[0];else if(0===arguments.length)return this.element[0].value;return this};this.on=function(a,b){for(var c=0;c<this.element.length;c++){var d=this.element[c];d.addEventListener(a,b.bind(d))}return this};this.addClass=function(a){for(var b=0;b<this.element.length;b++)this.element[b].classList.add(a);return this};this.removeClass=function(a){for(var b=0;b<this.element.length;b++)this.element[b].classList.remove(a);
return this};this.child=function(a){if("object"===typeof a)if(a.hasOwnProperty("CUSTOME"))this.element=a.element;else{for(var b=array(),c=0;c<this.element.length;c++)b.push.apply(temElement,this.element[c].querySelectorAll(a));this.element=b}else this.element=a;return this};this.each=function(a){for(var b=0;b<this.element.length;b++)a.bind(this.element[b])();return this};this.ajax=function(a){"undefined"==typeof a&&(a={});a.hasOwnProperty("type")||(a.type="get");a.hasOwnProperty("url")||(a.url="/");
a.hasOwnProperty("async")||(a.async=!1);a.hasOwnProperty("args")||(a.args="");a.hasOwnProperty("readystatechange")||(a.readystate=function(){});return this};return this}function get(d){var a=new XMLHttpRequest;return a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP"),a.open("GET",d,!1),a.send(),a.responseText}
function post(d,a,b,c){return("false"==typeof c||"undefined"==typeof c)&&(c=function(){}),"false"==typeof b|"undefined"==typeof b&&(b=!1),xmlhttp=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP"),xmlhttp.open("POST",d,b),xmlhttp.setRequestHeader("Content-type","application/x-www-form-urlencoded"),xmlhttp.onreadystatechange=c.bind(xmlhttp),xmlhttp.send(a),xmlhttp}function trim(d,a){return"false"==typeof a&&(a=5),d.substr(0,a)}
function changeAddr(d){window.history.pushState("","",d)};
